# Generated by Django 4.2.2 on 2023-06-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
